server:
  port: 9527
zuul:
  prefix: /services
  ignored-services: "*"
  routes:
    system:
      path: /system/**
      serviceId: SYSTEM-SERVICE
    course:
      path: /course/**
      serviceId: COURSE-SERVICE
    course:
      path: /file/**
      serviceId: FILE-SERVICE

# zuul的hystrix超时配置
hystrix:
  command:
    course-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
#配置zuul的ribbon的超时时间
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000